-- First, remove the table if it exists
drop table if exists bookmarks;

--Create the table anew
create table bookmarks (
    id INTEGER primary key generated by default as identity,
    title text,
    rating numeric,
    chapter text
);

--insert some test data
--Using a multi-row insert statement here

insert into bookmarks (id, title, rating, chapter)
values
    (1, 'The Power Of One', '5', 'Chapter 4'),
    (2, 'War and Peace', '3', 'Chapter 10'),
    (3, 'The Great Gatsby', '4', 'Chapter 3'),
    (4, 'Of Mice and Men', '2', 'Chapter 2'),
    (5, 'Moby Dick', '4', 'Chapter 30'),
    (6, 'Lolita', '2', 'Chapter 2'),
    (7, 'Ulysses', '1', 'Chapter 9'),
    (8, 'In Search of Lost Time', '4', 'Chapter 8'),
    (9, 'One Hundred Years of Solitude', '3', 'Chapter 6'),
    (10, 'Don Quixote', '5', 'Chapter 8');